name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Verify git version
      run:  git --version | grep "^git version $(cat git-version.txt)$"
    - name: Show git commands
      run:  git help -a 
    - name: Show list of git commands
      run:  git help -a | grep "^   [a-z]" | awk '{print $1}'
    - name: Compare git commands with git-commands.txt
      run:  diff <(git help -a | grep "^   [a-z]" | awk '{print $1}') git-commands.txt
