name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Verify git version
      run:  git --version | grep "^git version $(cat git-version.txt)$"
    - name: Show git commands
      run:  git help -a
    - name: Show list of git commands
      run:  git help -a | grep "^   [a-z]" | awk '{print $1}' | sort
    - name: Compare git commands with git-commands.txt
      run:  diff <(git help -a | grep "^   [a-z]" | awk '{print $1}' | sort) git-commands.txt
    - name: git init help
      run:  |
        git init --help | grep -o -- "--[a-z-]*" | sort | uniq
        diff <(git init --help | grep -o -- "--[a-z-]*" | sort | uniq) commands/git-init-options.txt
        git init --help
    - name: git init (normal usage)
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git init
        git config user.email "user1@gmail.com"
        git config user.name "User 1"
        ls -la
        git status
        echo "content" > file-1.txt
        git add file-1.txt
        echo "added"
        git status
        git commit -m "added file-1.txt"
        git status
        git log
    - name: git init --bare / status
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git init --bare
        if test git status
        then
          echo "should have failed"
        fi
    - name: command 1.3 - git init (twice)
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git init .
        git init .
