name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Verify git version
      run:  git --version | grep "^git version $(cat git-version.txt)$"
    - name: Show git commands
      run:  git help -a 
    - name: Show list of git commands
      run:  git help -a | grep "^   [a-z]" | awk '{print $1}' | sort
    - name: Compare git commands with git-commands.txt
      run:  diff <(git help -a | grep "^   [a-z]" | awk '{print $1}' | sort) git-commands.txt
    - name: command 1 - git init help
      run:  git init --help
    - name: command 1.1 - git init
      run:  |
        rm -rf ~/work 
        mkdir ~/work
        cd ~/work
        git init .
        ls -la
      
