name: git-add

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: git add help
      run:  |
        git add --help | grep -o -- "--[a-z-]*" | grep -v '^..$' | sort | uniq
        diff <(git add --help | grep -o -- "--[a-z-]*" | grep -v '^..$' | sort | uniq) commands/git-add-options.txt
        git add --help
    - name: git add (basic)
      run:  |
        cd ${HOME}
        rm -rf ${HOME}/workspace/git-add
        mkdir -p ${HOME}/workspace/git-add
        cd ${HOME}/workspace/git-add
        git init
        echo "a" > file-a.txt
        echo "b" > file-b.txt
        git status
        git add file-a.txt
        git status
    - name: git add --all
      run:  |
        cd ${HOME}
        rm -rf ${HOME}/workspace/git-add
        mkdir -p ${HOME}/workspace/git-add
        cd ${HOME}/workspace/git-add
        git init
        echo "a" > file-a.txt
        echo "b" > file-b.txt
        git status
        git add --all
        git status
    - name: git add --chmod=-x
      run:  |
        cd ${HOME}
        rm -rf ${HOME}/workspace/git-add
        mkdir -p ${HOME}/workspace/git-add
        cd ${HOME}/workspace/git-add
        git init --bare
        rm -rf ${HOME}/workspace-2
        mkdir -p ${HOME}/workspace-2
        cd ${HOME}/workspace-2
        git clone ${HOME}/workspace/git-add
        cd ${HOME}/workspace-2/git-add
        git config user.email "user1@gmail.com"
        git config user.name "User 1"
        echo '#!/bin/sh' > show-date.sh
        echo 'date' >> show-date.sh
        chmod +x show-date.sh
        git add --chmod=-x show-date.sh
        git commit -m "commit -x"
        git push origin
        git status
        ls -l show-date.sh
        mkdir -p ${HOME}/workspace-3
        cd ${HOME}/workspace-3
        git clone ${HOME}/workspace/git-add
        cd ${HOME}/workspace-3/git-add
        ls -l show-date.sh
