name: git-archimport

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: git archimport help
      run:  |
        git help ${GIT_COMMAND} || echo "archimport?"
