name: git-init

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: git init setup
      run:  |
        umask 007
    - name: git init help
      run:  |
        git init --help | grep -o -- "--[a-z-]*" | sort | uniq
        diff <(git init --help | grep -o -- "--[a-z-]*" | sort | uniq) commands/git-init-options.txt
        git init --help
    - name: git init (normal usage)
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git init
        git config user.email "user1@gmail.com"
        git config user.name "User 1"
        ls -la
        git status
        echo "content" > file-1.txt
        git add file-1.txt
        git status
        git commit -m "added file-1.txt"
        git status
        git log
    - name: git init --bare / status - incorrect usage
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git init --bare
        git status || echo
    - name: git init --bare - as repository
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git init --bare
        rm -rf ~/workspace-2
        mkdir ~/workspace-2
        cd ~/workspace-2
        git clone ~/workspace
        cd ~/workspace-2/workspace
        echo "Log of workspace-2"
        git log || echo
        git status || echo
        git config user.email "user1@gmail.com"
        git config user.name "User 1"
        echo "content" > file-1.txt
        git add file-1.txt
        git commit -m "added file-1.txt"
        git log
        git push origin
        rm -rf ~/workspace-3
        mkdir ~/workspace-3
        cd ~/workspace-3
        git clone ~/workspace
        cd ~/workspace-3/workspace
        echo "Log of workspace-3"
        git log || echo
        git status || echo
    - name: git init --separate-git-dir
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git status || echo
        git init --separate-git-dir=./.something-else
        ls -la
        cat .git
        git status || echo
    - name: git init --shared - share is not allowed (default)
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        git init --shared=false
        ls -ld .git
    - name: git init --shared - group share
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        umask
        git init --shared=true
        ls -ld .git
    - name: git init --shared - all
      run:  |
        cd ~
        rm -rf ~/workspace
        mkdir ~/workspace
        cd ~/workspace
        umask
        git init --shared=all
        ls -ld .git
